// @ts-check
const { RealmPlayerRoleEnum, RealmsPermissionRole } = require("@ore-ui-types/enums");
module.exports = /** @type {() => FacetTypeMap["vanilla.realmsStories.players"]} */ () => ({
    players: [
        {
            gamerTag: "xKingDark",
            xuid: "0",
            gamerIcon: "/src/assets/mcpreview.png",
            isOnline: true,
            role: RealmPlayerRoleEnum.OWNER,
            realmsRole: RealmsPermissionRole.Owner,
            realmStoriesRole: RealmPlayerRoleEnum.OWNER,
            fetchProfileStatus: 0,
            hasAccepted: true,
            hasOptedIn: true,
            isInRealm: true,
            lastSeenTime: 0,
        },
        {
            gamerTag: "xKingDark",
            xuid: "0",
            gamerIcon: "/src/assets/mcpreview.png",
            isOnline: true,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Admin,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            fetchProfileStatus: 0,
            hasAccepted: true,
            hasOptedIn: true,
            isInRealm: false,
            lastSeenTime: 0,
        },
        {
            gamerTag: "xKingDark",
            xuid: "0",
            gamerIcon: "/src/assets/mcpreview.png",
            isOnline: true,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            fetchProfileStatus: 0,
            hasAccepted: false,
            hasOptedIn: false,
            isInRealm: false,
            lastSeenTime: 0,
        },
        {
            gamerTag: "xKingDark",
            xuid: "0",
            gamerIcon: "/src/assets/mcpreview.png",
            isOnline: true,
            role: RealmPlayerRoleEnum.VISITOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.VISITOR,
            fetchProfileStatus: 0,
            hasAccepted: true,
            hasOptedIn: false,
            isInRealm: false,
            lastSeenTime: 0,
        },
        {
            gamerTag: "xKingDark",
            xuid: "0",
            gamerIcon: "/src/assets/mcpreview.png",
            isOnline: true,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            fetchProfileStatus: 0,
            hasAccepted: false,
            hasOptedIn: false,
            isInRealm: false,
            lastSeenTime: 0,
        },

        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Dustdroid",
            xuid: "2535420042871747",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "BluePurple2014",
            xuid: "2535430191802080",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "Unknown",
            xuid: "2535443725810634",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Dinolad55",
            xuid: "2535441079685861",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Diamond25cat",
            xuid: "2535439027468539",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Staz The Alien",
            xuid: "2535446856965483",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "SunsetMoment913",
            xuid: "2535450796893552",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Sadslug101",
            xuid: "2535408598237761",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Elmador 15",
            xuid: "2533274819315868",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "Snapped9699",
            xuid: "2535449191166044",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "Bluearch5",
            xuid: "2535429038232444",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "dalastdragon673",
            xuid: "2535419548443921",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "PufferFish53426",
            xuid: "2535438183245822",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "EnderPearl59",
            xuid: "2535460331473137",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "FlattestElf525",
            xuid: "2535468055639969",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "D1amondShark",
            xuid: "2535468534600351",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "SilentSomethin",
            xuid: "2535450421498588",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "MinuteMeteor385",
            xuid: "2535424996312946",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Jujubuju17",
            xuid: "2535449792649239",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "LegoTheArlo",
            xuid: "2535410685005263",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "realPewsie",
            xuid: "2535457575000408",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "RamenUnicorn13",
            xuid: "2535466114448987",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "HaltingBull4295",
            xuid: "2535452529112037",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "PowerPuma398694",
            xuid: "2535423318734303",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "CornyCone626400",
            xuid: "2535415336266412",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Blackskull1963",
            xuid: "2535453842880200",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "NonstickKoala86",
            xuid: "2535412377621447",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "gabejwright15",
            xuid: "2535439853364148",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "AR EH5973",
            xuid: "2535467563434651",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Gl1tcheee",
            xuid: "2535418564960518",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Jknotserious",
            xuid: "2535413675136720",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "LordFezziwig",
            xuid: "2535457857865733",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "FuzzyJungle54",
            xuid: "2535465676778027",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Epicgamer9254",
            xuid: "2535416169828910",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "RepliedBison766",
            xuid: "2535466117429814",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "BESTPVPER1350",
            xuid: "2535417000825919",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "MyrHelliosss",
            xuid: "2535442137338913",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "JadeShadow5358",
            xuid: "2535461495093994",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "spoonro wallace",
            xuid: "2533274838086954",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OWNER,
            realmsRole: RealmsPermissionRole.Owner,
            realmStoriesRole: RealmPlayerRoleEnum.OWNER,
            gamerIcon: "/src/assets/facet_resources/profile_pictures/8Crafter.gif",
            gamerTag: "Andexter8",
            xuid: "2535440895442815",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "MaZMurDa8421",
            xuid: "2535441956629145",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Luna D1766",
            xuid: "2535467847227973",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "ZeroMusic735278",
            xuid: "2535473055904028",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Noahthelastbear",
            xuid: "2535427302956590",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Romfish2013",
            xuid: "2535455023639153",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Prof7274",
            xuid: "2535472022477012",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "YT8Crafter",
            xuid: "2535414770201901",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "InsaneNote13780",
            xuid: "2535454740411740",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "bparko02",
            xuid: "2535462779396404",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "Nelsonkids1",
            xuid: "2535438939106521",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "ayben194",
            xuid: "2535440147056650",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Dinnerbone4995",
            xuid: "2535416687977715",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "april13lewis",
            xuid: "2535469457309765",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "BlackSkull1964",
            xuid: "2535407060809438",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Waffleking735",
            xuid: "2535440761917210",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "JKG020508",
            xuid: "2535439968410505",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "ShiningNote1745",
            xuid: "2535471957627216",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Felix sgg",
            xuid: "2535438614872558",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Batwin5169",
            xuid: "2535444956372022",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "BUBBLYxBUBBLE",
            xuid: "2535434762853850",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "ZachGaming1634",
            xuid: "2535427225560503",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "XS dark pro",
            xuid: "2535419731761295",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "B3bopBoom",
            xuid: "2535465982533835",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "EvanDidi2012",
            xuid: "2535443763430922",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "EsteemedRug3087",
            xuid: "2535450898802195",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Jonathan Pro939",
            xuid: "2535453027362373",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "biker1109",
            xuid: "2535469167337454",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "HereIsDino",
            xuid: "2535407031336773",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "CBW0106",
            xuid: "2535468686504292",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Arc1232644",
            xuid: "2535420175470919",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Camzombie 62",
            xuid: "2535448851658401",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "bionicTILM",
            xuid: "2535461122212387",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "ChaffyBat154227",
            xuid: "2535471251948348",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "SidedTundra6982",
            xuid: "2533275004489828",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Hippo3333",
            xuid: "2535410337514683",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Venomous Ace579",
            xuid: "2535450429060587",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "TumulousScarf84",
            xuid: "2535463908082210",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "TheLegendary755",
            xuid: "2535420200535247",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "BlakersBlakers5",
            xuid: "2535450749399023",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Kodak2547",
            xuid: "2535440816031117",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Subzero881929",
            xuid: "2535405389612585",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "JadePark6070843",
            xuid: "2535460414733092",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Badgirlhalo7263",
            xuid: "2535457861089668",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "VestingBead1798",
            xuid: "2535444368182231",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "Cya shaker",
            xuid: "2535443630523864",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "SashaS555",
            xuid: "2535426796675283",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "bedless5202",
            xuid: "2535418461866715",
        },
        {
            hasAccepted: true,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "CokeBoyMontana5",
            xuid: "2535472883780902",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "GamePlate723904",
            xuid: "2535413975095457",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "Ntho Sraom4009",
            xuid: "2535423299191954",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "MattChewy517",
            xuid: "2535455498519995",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "Aptstorm445",
            xuid: "2535421095793472",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "Gmod1621",
            xuid: "2535443667204572",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "OZAZ11",
            xuid: "2535458226112220",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "CarekTe",
            xuid: "2535425153159991",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "Cjgaming2056496",
            xuid: "2535473592732901",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "LAV3ND3R7205",
            xuid: "2535450732952979",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "Buddy8975",
            xuid: "2533274931234973",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "Reira7239",
            xuid: "2535406146902534",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "Lennonturtle647",
            xuid: "2535464536952171",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "Lightseeker2312",
            xuid: "2535433663035093",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "Horizon8969",
            xuid: "2535423596864075",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "Ggalacity",
            xuid: "2535427206324631",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "TragicJezter",
            xuid: "2535419162431232",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "AndrewS334422",
            xuid: "2535442157600678",
        },
        {
            hasAccepted: false,
            hasOptedIn: false,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.NONMEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.NONMEMBER,
            gamerIcon: "",
            gamerTag: "FortyOsprey101",
            xuid: "2535425339028006",
        },

        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 1786876475,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "MORONNIF13",
            xuid: "2535465562441515",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "BuriedChip",
            xuid: "2533274795328364",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 1787110560,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "isddf",
            xuid: "2535441091097679",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 1787110684,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Alexroibu1443",
            xuid: "2535463750558975",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 1784764190,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "SpanCloud1457",
            xuid: "2535470835077717",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 1787166917,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Admin,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "ewoker17",
            xuid: "2535471255357250",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "Chains2705",
            xuid: "2535467674616584",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 1785904499,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.OPERATOR,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.OPERATOR,
            gamerIcon: "",
            gamerTag: "NthAchiever9888",
            xuid: "2535450734011560",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 1785014964,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "steve90098760",
            xuid: "2535408174130432",
        },
        {
            hasAccepted: true,
            hasOptedIn: true,
            fetchProfileStatus: 2,
            lastSeenTime: 0,
            isInRealm: false,
            isOnline: false,
            role: RealmPlayerRoleEnum.MEMBER,
            realmsRole: RealmsPermissionRole.Player,
            realmStoriesRole: RealmPlayerRoleEnum.MEMBER,
            gamerIcon: "",
            gamerTag: "AbusingSpore414",
            xuid: "2535432275477443",
        },
    ],
    fetchOnlineMembersStatus: 2,
    fetchMembersStatus: 2,
});
